# Import Necessary Liabry

In [28]:
## importing the neccessary liabry
import numpy as np
import pandas as pd

# Load the data into pandas dataframe

In [29]:
data = pd.read_csv('practicing_data_preprocessing_data.csv')


# Store the all independent features into the X variable and all the dependent feature into the y variable

In [30]:
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values


# Handle Missing Values

In [31]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:4])
X[:, 1:4] = imputer.transform(X[:, 1:4])
print(X)

[['India' 34.0 92000.0]
 ['Sri lanka' 22.0 25000.0]
 ['China' 31.0 74000.0]
 ['Sri lanka' 29.0 54857.142857142855]
 ['China' 55.0 98000.0]
 ['India' 24.0 30000.0]
 ['Sri lanka' 28.0 40000.0]
 ['India' 33.714285714285715 60000.0]
 ['China' 51.0 89000.0]
 ['India' 44.0 78000.0]
 ['Sri lanka' 21.0 20000.0]
 ['China' 25.0 30000.0]
 ['India' 33.0 45000.0]
 ['India' 42.0 65000.0]
 ['Sri lanka' 33.0 22000.0]]


## Encoding the categorical data

### Encodign the X or the independent values

In [32]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X) 

[[0.0 1.0 0.0 34.0 92000.0]
 [0.0 0.0 1.0 22.0 25000.0]
 [1.0 0.0 0.0 31.0 74000.0]
 [0.0 0.0 1.0 29.0 54857.142857142855]
 [1.0 0.0 0.0 55.0 98000.0]
 [0.0 1.0 0.0 24.0 30000.0]
 [0.0 0.0 1.0 28.0 40000.0]
 [0.0 1.0 0.0 33.714285714285715 60000.0]
 [1.0 0.0 0.0 51.0 89000.0]
 [0.0 1.0 0.0 44.0 78000.0]
 [0.0 0.0 1.0 21.0 20000.0]
 [1.0 0.0 0.0 25.0 30000.0]
 [0.0 1.0 0.0 33.0 45000.0]
 [0.0 1.0 0.0 42.0 65000.0]
 [0.0 0.0 1.0 33.0 22000.0]]


### Encoding the dependent values or y

In [33]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[1 1 1 0 1 0 0 0 1 1 0 1 1 1 0]


## Spliting the data into train test split

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1)

In [35]:
print(X_train)

[[1.0 0.0 0.0 31.0 74000.0]
 [0.0 0.0 1.0 21.0 20000.0]
 [1.0 0.0 0.0 55.0 98000.0]
 [0.0 0.0 1.0 22.0 25000.0]
 [0.0 1.0 0.0 42.0 65000.0]
 [0.0 1.0 0.0 34.0 92000.0]
 [0.0 0.0 1.0 33.0 22000.0]
 [0.0 1.0 0.0 44.0 78000.0]
 [1.0 0.0 0.0 51.0 89000.0]
 [0.0 1.0 0.0 33.0 45000.0]
 [1.0 0.0 0.0 25.0 30000.0]
 [0.0 1.0 0.0 24.0 30000.0]]


In [36]:
print(X_test)

[[0.0 0.0 1.0 29.0 54857.142857142855]
 [0.0 1.0 0.0 33.714285714285715 60000.0]
 [0.0 0.0 1.0 28.0 40000.0]]


In [37]:
y_train

array([1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0])

In [38]:
y_test

array([0, 0, 0])

#3 Feature Scalling(It should do after train test split)

In [44]:
print(X_train[:, 3:].shape)

(12, 2)


In [47]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.fit_transform(X_test[:, 3:])

In [48]:
print(X_train)

[[1.0 0.0 0.0 -0.33235613578162815 0.637555294512461]
 [0.0 0.0 1.0 -1.2598616309861719 -1.2403348456878782]
 [1.0 0.0 0.0 1.8936570527092769 1.4721731346015006]
 [0.0 0.0 1.0 -1.1671110814657175 -1.0664561290026617]
 [0.0 1.0 0.0 0.6878999089433699 0.324573604479071]
 [0.0 1.0 0.0 -0.05410448722026508 1.2635186745792406]
 [0.0 0.0 1.0 -0.14685503674071945 -1.1707833590137917]
 [0.0 1.0 0.0 0.8734010079842788 0.7766582678606342]
 [1.0 0.0 0.0 1.5226548546274594 1.1591914445681106]
 [0.0 1.0 0.0 -0.14685503674071945 -0.37094126226179536]
 [1.0 0.0 0.0 -0.8888594329043545 -0.892577412317445]
 [0.0 1.0 0.0 -0.9816099824248089 -0.892577412317445]]


In [49]:
print(X_test)

[[0.0 0.0 1.0 -0.49688584623919657 0.38185378196002606]
 [0.0 1.0 0.0 1.3951025682869713 0.988327435661243]
 [0.0 0.0 1.0 -0.8982167220477776 -1.3701812176212664]]
